### ISSUE TITLE
Contact page background issue.

### ISSUE THREAD

**Issue by bedanta12** [bedanta12/my-portfolio#18] opened 2023-10-11 17:37 UTC
When the contact page is called, it slides up to show the information in it. Now the problem arises when the user tries to interact with the page outside of the contact page. When cursor interacted outside the contact page, while the page is opened, the website interacts.

You must change the code so that whenever the contact page is opened, on clicking outside the contact page closes the contact page and scrolling won't work.

Refer to the video below to understand the issue.

https://github.com/bedanta12/my-portfolio/assets/105166766/1bf268be-4b1f-4b4c-b0a8-3c7443e156e1

**Comment by nitinryali** [comment] 2023-10-11 17:39
Please Assign this to me

**Comment by nitinryali** [comment] 2023-10-11 18:21
sure I'll try to complete asap

**Comment by Dhruv127** [comment] 2023-10-12 19:47
can you assign me ?

**Comment by Sofiyana-1811** [comment] 2023-10-12 20:02
@Dhruv127 we also want the scrolling of the background to stop when contact page is being viewed.

**Comment by Dhruv127** [comment] 2023-10-12 20:15
ok , kindly assign to me.

**Comment by Sofiyana-1811** [comment] 2023-10-12 20:21
@Dhruv127 I will be assigning this issue to you, please solve it by 14th Oct EOD. Feel free to ask questions or to tell us if you require more time.

**Comment by Dhruv127** [comment] 2023-10-13 08:31
Check PR #24

**Comment by shaurya-jain23** [comment] 2023-10-13 23:26
I would like to work on this, if it is not completed

**Comment by Dhruv127** [comment] 2023-10-16 05:26
Can you merge if the issue is resolved?

**Comment by aarjun8060** [comment] 2023-10-16 17:16
Please assign this to me

**Closed** 2023-10-16 19:49 UTC
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest2023
